import { describe, expect, test } from "vitest";
import { useSharedSite } from "#test/test-site-factory.js";

// Test the actual feed output using isolated test sites
// Tests are grouped to minimize builds while maintaining test isolation

// Factory: setup and teardown a test site within a describe block
const setupTestSiteWithFeed = (siteOptions) => {
  const getSite = useSharedSite(siteOptions);
  return { getSite, getFeed: () => getSite().getOutput("feed.xml") };
};

describe("feed", () => {
  // --- Comprehensive test site (covers most feed tests) ---
  // Single build for tests that can share the same content
  describe("comprehensive site", () => {
    const { getSite, getFeed } = setupTestSiteWithFeed({
      dataFiles: [
        {
          filename: "site.json",
          data: {
            name: "Test Blog Name",
            url: "https://test.invalid",
            description: "Test site",
          },
        },
      ],
      files: [
        {
          path: "news/2024-01-01-older.md",
          frontmatter: {
            name: "Older Post",
            blocks: [
              {
                type: "markdown",
                content: "Check out [our homepage](/) for more info.",
              },
            ],
          },
          content: "",
        },
        {
          path: "news/2024-06-15-newer.md",
          frontmatter: {
            name: "Newer Post",
            blocks: [{ type: "markdown", content: "Second post content." }],
          },
          content: "",
        },
        {
          path: "news/special.md",
          frontmatter: {
            name: "Tom and Jerry's Adventure",
            blocks: [{ type: "markdown", content: "Special chars test" }],
          },
          content: "",
        },
        {
          path: "news/ampersand.md",
          frontmatter: {
            name: "Marquee Weddings & Photo Booths",
            blocks: [{ type: "markdown", content: "Ampersand test" }],
          },
          content: "",
        },
      ],
    });

    // --- File Generation ---
    test("Feed XML file is generated by the build", () => {
      expect(getSite().hasOutput("feed.xml")).toBe(true);
    });

    // --- Atom XML Structure ---
    test("Feed is valid Atom XML", () => {
      const feed = getFeed();
      expect(feed.includes('<?xml version="1.0"')).toBe(true);
      expect(feed.includes('<feed xmlns="http://www.w3.org/2005/Atom"')).toBe(
        true,
      );
      expect(feed.includes("</feed>")).toBe(true);
    });

    test("Feed contains required Atom elements", () => {
      const feed = getFeed();
      expect(feed.includes("<title>")).toBe(true);
      expect(feed.includes("<id>")).toBe(true);
      expect(feed.includes("<updated>")).toBe(true);
      expect(feed.includes("<author>")).toBe(true);
    });

    test("Feed has self-referencing link", () => {
      const feed = getFeed();
      expect(feed.includes('rel="self"')).toBe(true);
      expect(feed.includes("/feed.xml")).toBe(true);
    });

    // --- Entry Structure ---
    test("Feed contains entry elements for blog posts", () => {
      const feed = getFeed();
      expect(feed.includes("<entry>")).toBe(true);
      expect(feed.includes("</entry>")).toBe(true);
      expect(feed.includes("Older Post")).toBe(true);
      expect(feed.includes("Newer Post")).toBe(true);
    });

    test("Feed entries have content with absolute URLs", () => {
      const feed = getFeed();
      expect(feed.includes('<content type="html">')).toBe(true);
      // Links in content should be absolute (transformed by htmlBase plugin)
      expect(feed.includes('href="https://')).toBe(true);
    });

    test("Feed entries are ordered with most recent first", () => {
      const feed = getFeed();
      const olderPos = feed.indexOf("Older Post");
      const newerPos = feed.indexOf("Newer Post");

      expect(olderPos > 0).toBe(true);
      expect(newerPos > 0).toBe(true);
      expect(newerPos < olderPos).toBe(true);
    });

    // --- Site Configuration ---
    test("Feed title matches configured site name", () => {
      expect(getFeed().includes("<title>Test Blog Name</title>")).toBe(true);
    });

    // --- Special Characters ---
    test("Feed is valid XML with special characters in titles", () => {
      const feedXml = getFeed();
      expect(feedXml.includes("<entry>")).toBe(true);
      expect(feedXml.includes("Tom and Jerry")).toBe(true);
      // Apostrophe should be handled (either escaped or in CDATA)
      expect(
        feedXml.includes("Jerry's") || feedXml.includes("Jerry&#39;s"),
      ).toBe(true);
    });

    test("Feed escapes ampersands in entry titles", () => {
      const feed = getFeed();
      // The raw `&` would produce invalid XML; it must be escaped to `&amp;`
      expect(
        feed.includes("<title>Marquee Weddings &amp; Photo Booths</title>"),
      ).toBe(true);
      expect(feed.includes("Weddings & Photo")).toBe(false);
    });
  });

  // --- Edge case: No posts site (needs separate build) ---
  describe("with no posts", () => {
    const { getSite, getFeed } = setupTestSiteWithFeed({
      files: [
        {
          path: "pages/about.md",
          frontmatter: {
            name: "About",
            blocks: [{ type: "markdown", content: "# About us" }],
          },
          content: "",
        },
      ],
    });

    test("Feed is generated even when there are no blog posts", () => {
      expect(getSite().hasOutput("feed.xml")).toBe(true);
      expect(
        getFeed().includes('<feed xmlns="http://www.w3.org/2005/Atom"'),
      ).toBe(true);
      // With no posts, there should be no entries
      expect(!getFeed().includes("<entry>")).toBe(true);
    });
  });
});
